import pandas as pd
import re
df = pd.read_csv(
    "Data/date=30_datasetid=2602e94520abf8dbeefa5a9ff48f6462_assetid=a65a32c46672819e3e0375acb58edbbd_revid=3daefcd51d6266cf6c1e517732104e1a.csv",
    sep="|"
)

df = df[df["VINTAGE YEAR"].between(2010, 2024)]
"""
"continuation fund" are all false  and "linked continuation fund" are all NaN


"""

funds = [
    "MANAGER REGION", "MANAGER ADDRESS", "MANAGER CITY", "MANAGER STATE",
    "MANAGER ZIP CODE", "MANAGER COUNTRY", "MANAGER WEBSITE", "MANAGER EMAIL",
    "MANAGER TEL", "MANAGER FAX", "MANAGER SECONDARY LOCATIONS",
    "FUND MANAGER", "FUND STRUCTURE", "FUND SIZE (EUR MN)",
    "ALTERNATIVE NAMES", "FUND SERIES ID", "FUND SERIES NAME","CONTINUATION FUND","LINKED CONTINUATION FUND",
    "ESG TRANSPARENCY"  , "ESG GOVERNANCE RISK"  , "ESG SOCIAL RISK"  , "ESG ENVIRONMENTAL RISK"  , 
    "OVERVIEW" ,"SUBSCRIPTION CREDIT FACILITY" ,"PERCENTAGE OF RETURNING LPS","NUMBER OF LPS (MAX)","NUMBER OF LPS (MIN)", 
    "NUMBER OF LPS (ESTIMATED)", "LP BREAKDOWN BY TYPE", "LP BREAKDOWN BY LOCATION","CO-INVESTMENT CAPITAL AMOUNT (USD MN)",
    "CO-INVESTMENT CAPITAL AMOUNT (CURR MN)","CO-INVESTMENT CAPITAL CURRENCY","CO-INVESTMENT COMMITMENTS (USD MN)",
    "CO-INVESTMENT COMMITMENTS (CURR MN)","CO-INVESTMENT COMMITMENTS CURRENCY","FUND CURRENCY","FUNDS RAISED (CURR MN)" ,
    "FUNDS RAISED CURRENCY","TOTAL CAPITAL COMMITMENTS (CURR MN)","TOTAL CAPITAL COMMITMENTS CURRENCY","PAID IN CAPITAL (CURR MN)",
    "PAID IN CAPITAL CURRENCY","TOTAL ASSETS (CURR MN)","OTHER GEOGRAPHIES","UNREALISED VALUE (MN)","AUM (MN)","DRY POWDER AS AT DATE"
    ,"DRY POWDER (MN)","PREVIOUS FUND ID","OVERVIEW","SUBSCRIPTION CREDIT FACILITY","PERCENTAGE OF RETURNING LPS","NUMBER OF LPS (MAX)","NUMBER OF LPS (MIN)"
    ,"GP COMMITMENTS TO FUND (% OF TOTAL)","ADVISORY BOARD LP REPRESENTATION","FUND FORMATION COSTS (MN)","FUND FORMATION COSTS (MN)","LP MAJORITY REQUIRED (%)"
    ,"NO-FAULT DIVORCE CLAUSE?","SHARE OF TRANSACTION FEES REBATED TO LP (%)","KEY MAN CLAUSE","HURDLE RATE (%)","GP CATCH UP RATE (%)","CARRIED INTEREST (%)","CARRIED INTEREST STRUCTURE","CARRIED INTEREST PAID ON","CARRIED INTEREST PAID AS"
    ,"MGR MANAGEMENT FEE (%)","MGMT FEE PAID ON","MGMT FEE PAID AS","FUND TERM (YRS)","FUND TERM EXTENSION OPTIONS (YRS)","FUND TERM EXTENSIONS (YRS USED)",
    "MECHANISM FOR MGMT FEE REDUCTIONS - POST-INVESTMENT PERIOD","INVESTMENT PERIOD (YRS)","CHARGE FREQUENCY","MGMT FEE RATE (%) DURING INV PERIOD","AUDITOR","ADMINISTRATOR","LAW FIRMS" , "PLACEMENT AGENTS" , "PE INVESTMENT SIZE PER PORTFOLIO COMPANY (MAX)"
    ,"PE INVESTMENT SIZE PER PORTFOLIO COMPANY (MIN)","PE INVESTMENT SIZE PER PORTFOLIO COMPANY (TYPICAL)","PE PREFERRED EQUITY INVESTMENTS?",
    "PE USE OF LEVERAGE?","PE MAXIMUM LEVERAGE RATIO","PE AVERAGE LEVERAGE RATIO",
    "PE TARGETED INDUSTRIES","PE TARGETED GEOGRAPHIES","PE STAGE FOCUS","PE EXIT ROUTES","DOMICILE","FUND ETHOS","FUND LEGAL STRUCTURE" , "FUND NUMBER (OVERALL)","SINGLE DEAL FUND","LIFESPAN EXTENSION"
    ,"SOLELY FINANCED BY MANAGEMENT" ,"TARGET IRR - NET MIN", "TARGET IRR - NET MAX","TARGET IRR - GROSS MIN","TARGET IRR - GROSS MAX","INITIAL TARGET (CURR MN)","INITIAL TARGET (USD MN)","HARD CAP (CURR MN)"
    ,"HARD CAP (USD MN)", "FUND RAISING LAUNCH DATE","LATEST INTERIM CLOSE DATE","LATEST INTERIM CLOSE SIZE (CURR MN)","LATEST INTERIM CLOSE SIZE (USD MN)","LATEST INTERIM CLOSE SIZE (EUR MN)","ESTIMATED LAUNCH","FINAL CLOSE SIZE (CURR MN)",
    "FINAL CLOSE SIZE (EUR MN)","FIRST CLOSE SIZE (CURR MN)","FIRST CLOSE SIZE (EUR MN)","TOTAL NUMBER OF CLOSINGS","OFFER CO-INVESTMENT OPPORTUNITIES TO LPS?","CO-INVESTMENT CAPITAL AMOUNT (EUR MN)","MONTHS TO FIRST CLOSE","MONTHS IN MARKET"
    ,"BUYOUT FUND LEVERAGE (%)","MGMT FEE RATE (%) - POST-INVESTMENT PERIOD","SPECIAL PROVISION FOR LARGER LPS","CARRIED INTEREST BASIS", "COUNTRIES" , "REGIONS","FUND NUMBER (SERIES)","LIFESPAN (YEARS)","SOLELY FINANCED BY","INITIAL TARGET (EUR MN)","HARD CAP (EUR MN)"
    "INDUSTRY VERTICALS","FUND SIZE (CURR MN)","GEOGRAPHIC FOCUS","GEOGRAPHIC EXPOSURE","FIRM ID","NAME","INDUSTRY VERTICALS","HARD CAP (EUR MN)"
]

df.drop(columns=funds, inplace=True, errors="ignore")

# Ensure integer type
df["VINTAGE YEAR"] = pd.to_numeric(df["VINTAGE YEAR"], errors="coerce").astype("Int64")

df=df[df["PRIMARY GEOGRAPHIC FOCUS"] == "North America"]


df=df[df['ASSET CLASS']=='Venture Capital']


# --- Sort globally by FUND ID, then VINTAGE YEAR ---
df = df.sort_values(by=[ "VINTAGE YEAR", "FUND ID"], ascending=[True, True]).reset_index(drop=True)
df["CORE INDUSTRIES"] = df["CORE INDUSTRIES"].str.split(";")
df = df.explode("CORE INDUSTRIES")

# Clean extra spaces
df["CORE INDUSTRIES"] = df["CORE INDUSTRIES"].str.strip()

df["INDUSTRIES"] = df["INDUSTRIES"].apply(
    lambda x: re.split(r"[;&/\\]+", str(x))
)
df["INDUSTRIES"] = df["INDUSTRIES"].apply(
    lambda lst: [s.strip() for s in lst if s.strip()]
)

# --- 2️⃣ One-hot encode ---
industry_features = df["INDUSTRIES"].explode().str.get_dummies().groupby(level=0).max()

# --- 3️⃣ Clean column names ---
industry_features.columns = (
    industry_features.columns.str.replace(r"[^\w]+", "_", regex=True)
)

# --- ✅ 4️⃣ Reset index before concatenation ---
df_reset = df.reset_index(drop=True)
industry_features_reset = industry_features.reset_index(drop=True)

df_final = pd.concat([df_reset.drop(columns=["INDUSTRIES"]), industry_features_reset], axis=1)

drop_Again=["ASSET CLASS", "PRIMARY GEOGRAPHIC FOCUS","TARGET SIZE (CURR MN)","TARGET SIZE (EUR MN)","HARD CAP (EUR MN)","LATEST CLOSE DATE","FINAL CLOSE DATE","DATE ADDED"]
df_final.drop(columns=drop_Again, inplace=True, errors="ignore")
df_final.to_csv("filtered_funds.csv", index=False)
print(f"✅ Filtered dataset saved → filtered_funds.csv ({df_final.shape[0]} rows, {df_final.shape[1]} cols)")
